import type { Project, Location } from "@/types/project";
import { geoToMap } from "@/lib/geo";

export const projects: Project[] = [
  {
    id: "flexi-stylus",
    name: "Flexi Stylus 2.0",
    description: "Robot arm control dashboard with 3D visualization and real-time telemetry",
    url: "http://localhost:3001",
    thumbnail: "/thumbnails/flexi-stylus.png",
    tags: ["Three.js", "Robotics", "React"],
    color: "#22c55e",
  },
  {
    id: "shader-playground",
    name: "Shader Playground",
    description: "Interactive GLSL shader editor with live preview and hot reload",
    url: "http://localhost:3002",
    thumbnail: "/thumbnails/shader-playground.png",
    tags: ["Three.js", "GLSL", "WebGL"],
    color: "#8b5cf6",
  },
  {
    id: "particle-system",
    name: "Particle System",
    description: "GPU-accelerated particle system with physics simulation",
    url: "http://localhost:3003",
    thumbnail: "/thumbnails/particle-system.png",
    tags: ["Three.js", "Compute Shaders", "Physics"],
    color: "#f97316",
  },
  {
    id: "procedural-terrain",
    name: "Procedural Terrain",
    description: "Infinite procedural terrain generator with biomes and erosion",
    url: "http://localhost:3004",
    thumbnail: "/thumbnails/procedural-terrain.png",
    tags: ["Three.js", "Procedural", "Noise"],
    color: "#06b6d4",
  },
  {
    id: "physics-sandbox",
    name: "Physics Sandbox",
    description: "Interactive 3D physics sandbox with real-time rigid body simulation",
    url: "http://localhost:3005",
    thumbnail: "/thumbnails/physics-sandbox.png",
    tags: ["Three.js", "Rapier", "Physics"],
    color: "#ec4899",
  },
  {
    id: "audio-visualizer",
    name: "Audio Visualizer",
    description: "Real-time 3D audio visualization with frequency analysis",
    url: "http://localhost:3006",
    thumbnail: "/thumbnails/audio-visualizer.png",
    tags: ["Three.js", "Web Audio", "Shaders"],
    color: "#eab308",
  },
];

export const locations: Location[] = [
  {
    id: "ait-giefinggasse",
    name: "AIT Giefinggasse",
    description: "Austrian Institute of Technology, Wien Floridsdorf",
    geo: { lat: 48.2225, lng: 16.3841 },
    mapPosition: geoToMap({ lat: 48.2225, lng: 16.3841 }),
    stations: [
      {
        id: "ait-building",
        name: "AIT Building",
        description: "Main research building of the Austrian Institute of Technology",
        url: "http://localhost:4001",
        position: [0, 0, 0],
        tags: ["Research", "Headquarters"],
        color: "#3b82f6",
      },
      {
        id: "robot-forklift",
        name: "Robot Forklift",
        description: "Autonomous robotic forklift for industrial logistics",
        url: "http://localhost:4002",
        position: [15, 0, 6],
        tags: ["Robotics", "Logistics", "Autonomous"],
        color: "#f59e0b",
      },
      {
        id: "military-training",
        name: "Military Training Area",
        description: "Advanced military training and simulation facility",
        url: "http://localhost:4003",
        position: [-15, 0, 9],
        tags: ["Military", "Training", "Simulation"],
        color: "#65a30d",
      },
      {
        id: "police-vr",
        name: "Police VR Training",
        description: "VR-based police training with 3D-printed weapon replicas",
        url: "http://localhost:4004",
        position: [9, 0, -12],
        tags: ["VR", "Police", "3D Printing"],
        color: "#2563eb",
      },
      {
        id: "drone-flying",
        name: "Drone Flying Area",
        description: "Outdoor drone testing and flight operations area",
        url: "http://localhost:4005",
        position: [-9, 0, -15],
        tags: ["Drones", "UAV", "Testing"],
        color: "#8b5cf6",
      },
      {
        id: "human-drone-pad",
        name: "Human-Drone Transport Pad",
        description: "Landing pad for human-carrying drone transport systems",
        url: "http://localhost:4006",
        position: [21, 0, -9],
        tags: ["Drones", "Transport", "Aviation"],
        color: "#06b6d4",
      },
      {
        id: "hexapod-rescue",
        name: "Hexapod Rescue Robot",
        description: "Six-legged robot for search and rescue in collapsed structures",
        url: "http://localhost:4007",
        position: [-18, 0, -6],
        tags: ["Robotics", "Rescue", "Hexapod"],
        color: "#dc2626",
      },
      {
        id: "rescue-mannequin",
        name: "Rescue Training Mannequin",
        description: "Green mannequin for accident and emergency rescue training",
        url: "http://localhost:4008",
        position: [12, 0, 15],
        tags: ["Training", "Rescue", "Safety"],
        color: "#22c55e",
      },
      {
        id: "timber-crane",
        name: "Timber Crane Truck",
        description: "Heavy-duty timber crane mounted on truck chassis",
        url: "http://localhost:4009",
        position: [-12, 0, 18],
        tags: ["Crane", "Forestry", "Heavy Machinery"],
        color: "#ea580c",
      },
      {
        id: "steel-coil-crane",
        name: "Steel Coil Crane",
        description: "Industrial crane system for lifting steel coils",
        url: "http://localhost:4010",
        position: [24, 0, 15],
        tags: ["Crane", "Steel", "Industrial"],
        color: "#78716c",
      },
      {
        id: "airplane-disassembly",
        name: "Airplane Disassembly",
        description: "Aircraft maintenance and disassembly training facility",
        url: "http://localhost:4011",
        position: [-24, 0, 0],
        tags: ["Aviation", "Maintenance", "Training"],
        color: "#94a3b8",
      },
      {
        id: "vr-workspace",
        name: "VR Workspace",
        description: "Collaborative workspace with VR headsets for industrial design",
        url: "http://localhost:4012",
        position: [6, 0, -21],
        tags: ["VR", "Design", "Collaboration"],
        color: "#a855f7",
      },
    ],
  },
  {
    id: "vil-gusshausstrasse",
    name: "VIL Gusshausstraße",
    description: "Virtual Industrial Lab, TU Wien Campus, Wien",
    geo: { lat: 48.1983, lng: 16.3696 },
    mapPosition: geoToMap({ lat: 48.1983, lng: 16.3696 }),
    stations: [
      {
        id: "vil-building",
        name: "VIL Building",
        description: "Virtual Industrial Lab — immersive industrial research facility",
        url: "http://localhost:4020",
        position: [0, 0, 0],
        tags: ["VR", "Research", "Industrial"],
        color: "#0ea5e9",
      },
      {
        id: "flexi-stylus",
        name: "Flexi Stylus Robot Control",
        description: "Robot arm controlled by stylus for precision casting work",
        url: "http://localhost:3001",
        position: [9, 0, 6],
        tags: ["Robotics", "Stylus", "Casting"],
        color: "#22c55e",
      },
    ],
  },
  {
    id: "seibersdorf",
    name: "Seibersdorf",
    description: "AIT Seibersdorf Campus, Niederösterreich",
    geo: { lat: 47.9777, lng: 16.508 },
    mapPosition: geoToMap({ lat: 47.9777, lng: 16.508 }),
    stations: [
      {
        id: "crawler-robot",
        name: "Crawler Robot",
        description: "Tracked crawler robot for hazardous environment exploration",
        url: "http://localhost:4030",
        position: [0, 0, 0],
        tags: ["Robotics", "Crawler", "Exploration"],
        color: "#d97706",
      },
    ],
  },
  {
    id: "voestalpine-linz",
    name: "voestalpine Linz",
    description: "voestalpine AG Steelworks, Linz an der Donau",
    geo: { lat: 48.307, lng: 14.286 },
    mapPosition: geoToMap({ lat: 48.307, lng: 14.286 }),
    stations: [
      {
        id: "stahlwelt-museum",
        name: "Stahlwelt Museum",
        description: "Interactive steel museum showcasing voestalpine history and technology",
        url: "http://localhost:4040",
        position: [0, 0, 0],
        tags: ["Museum", "Steel", "Interactive"],
        color: "#0ea5e9",
      },
      {
        id: "blast-furnaces",
        name: "Blast Furnaces",
        description: "Massive blast furnace complex for iron production",
        url: "http://localhost:4041",
        position: [15, 0, 6],
        tags: ["Steel", "Industrial", "Heavy"],
        color: "#ef4444",
      },
      {
        id: "steel-plant",
        name: "Steel Plant",
        description: "Main steel production facility with rolling mills",
        url: "http://localhost:4042",
        position: [-12, 0, 9],
        tags: ["Steel", "Production", "Industrial"],
        color: "#78716c",
      },
    ],
  },
];
